name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Update DatabaseConfig.java
      run: |
        cat <<EOF > src/main/java/com/example/wadlogin/DatabaseConfig.java
        package com.example.wadlogin;

        public class DatabaseConfig {
            public static final String DB_URL = "${{ secrets.DB_URL }}";
            public static final String USER = "${{ secrets.DB_USER }}";
            public static final String PASS = "${{ secrets.DB_PASS }}";
        }
        EOF

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
